# Generated by Django 4.2.1 on 2023-07-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('street', models.CharField(default='None', max_length=255)),
                ('areaCode', models.CharField(default='None', max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='estate',
            old_name='address',
            new_name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='seller',
        ),
        migrations.AddField(
            model_name='estate',
            name='description',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(default=0),
        ),
    ]
