# Generated by Django 4.2.1 on 2023-07-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_app', '0002_address_rename_address_estate_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='area',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estate',
            name='baths',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estate',
            name='beds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estate',
            name='garages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estate',
            name='rent',
            field=models.BooleanField(default=False),
        ),
    ]
