# Generated by Django 4.2.1 on 2023-07-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_app', '0003_estate_area_estate_baths_estate_beds_estate_garages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estate',
            name='type',
        ),
        migrations.AddField(
            model_name='estate',
            name='stories',
            field=models.IntegerField(default=1),
        ),
    ]
